In [1]:
import numpy as np

__Задание 1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

*Вручную:*

   а) $AB$ не определено; $BA$ также не определено
   
   б) $AB$ — $2\times 3$, $BA$ — не определено
    
   в) $AB$ — $8\times 8$, $BA$ — $3\times 3$
    
   г) $AB$ — $4\times 4$, $BA$ — $4\times 4$

*С помощью numpy:*

a)

In [2]:
A = np.ones((4, 2))
B = np.ones((4, 2))

In [3]:
np.dot(A, B).shape

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [4]:
np.dot(B, A).shape

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

б)

In [5]:
A = np.ones((2, 5))
B = np.ones((5, 3))

In [6]:
np.dot(A, B).shape

(2, 3)

In [7]:
np.dot(B, A).shape

ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

в)

In [8]:
A = np.ones((8, 3))
B = np.ones((3, 8))

In [9]:
np.dot(A, B).shape

(8, 8)

In [10]:
np.dot(B, A).shape

(3, 3)

г)

In [11]:
A = np.ones((4, 4))
B = np.ones((4, 4))

In [12]:
np.dot(A, B).shape

(4, 4)

In [13]:
np.dot(B, A).shape

(4, 4)

__Задание 2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

*Вручную:*

$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} +
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = 
\begin{pmatrix}
1 + 4 & -2 - 1\\ 
3 + 0 & 0 + 5
\end{pmatrix} = 
\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}
$

$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \cdot
\begin{pmatrix}
4 & -1\\ 
0 & -5
\end{pmatrix} = 
\begin{pmatrix}
1\cdot 4 + (-2)\cdot 0 & 1\cdot (-1) + (-2)\cdot 5\\ 
3\cdot 4 + 0\cdot 0 & 3\cdot (-1) + 0\cdot 5
\end{pmatrix} = 
\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}
$

*С помощью numpy:*

In [14]:
A = np.array([[1, -2],
              [3, 0]])
B = np.array([[4, -1],
              [0, 5]])

In [15]:
A + B

array([[ 5, -3],
       [ 3,  5]])

In [16]:
np.dot(A, B)

array([[  4, -11],
       [ 12,  -3]])

__Задание 3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

*Вручную:*

$3 \cdot
\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}
-2 \cdot
\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}
+4 \cdot
\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}
=
\begin{pmatrix}
3\cdot 1 - 2\cdot 0 + 4\cdot 2 & 3\cdot 7 - 2\cdot 5 + 4\cdot (-4)\\ 
3\cdot 3 - 2\cdot 2 + 4\cdot 1 & 3\cdot (-6) - 2\cdot (-1) + 4\cdot 1
\end{pmatrix} = 
\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

*С помощью numpy:*

In [17]:
A = np.array([[1, 7],
              [3, -6]])
B = np.array([[0, 5],
              [2, -1]])
C = np.array([[2, -4],
              [1, 1]])

In [18]:
3 * A - 2 * B + 4 * C

array([[ 11,  -5],
       [  9, -12]])

__Задание 4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

*Вручную:*

$A^T=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$


$AA^{T}=
\begin{pmatrix}
4^2 + 1^2 & 4\cdot 5 + 1\cdot (-2) & 4\cdot 2 + 1\cdot 3\\ 
5\cdot 4 + (-2)\cdot 1 & 5^2 + (-2)^2 & 5\cdot 2 + (-2)\cdot 3\\ 
2\cdot 4 + 3\cdot 1 & 2\cdot 5 + 3\cdot (-2) & 2^2 + 3^2\\ 
\end{pmatrix} = 
\begin{pmatrix}
17&18&11\\
18&29&4\\
11&4&13\\
\end{pmatrix}
$

$A^{T}A=
\begin{pmatrix}
4^2 + 5^2 + 2^2 & 4\cdot 1 + 5\cdot (-2) + 2\cdot 3\\ 
1\cdot 4 + (-2)\cdot 5 + 3\cdot 2 & 1^2 + (-2)^2 + 3^2\\ 
\end{pmatrix} = 
\begin{pmatrix}
45&0\\
0&14\\
\end{pmatrix}
$

*С помощью numpy:*

In [19]:
A = np.array([[4, 1],
              [5, -2],
              [2, 3]])

In [20]:
np.dot(A, A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [21]:
np.dot(A.T, A)

array([[45,  0],
       [ 0, 14]])

__Задание 5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [22]:
def matrix_multiplication(A, B):

    return [[sum(a * b for a, b in zip(row, column)) for column in zip(*B)] for row in A] if len(A[0]) == len(B)\
    else 'Произведение матриц не определено'

In [23]:
A = [[1, 2], [3, 4], [5, 6]]
B = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [24]:
matrix_multiplication(A, B)

[[11, 14, 17, 20], [23, 30, 37, 44], [35, 46, 57, 68]]

In [25]:
matrix_multiplication(B, A)

'Произведение матриц не определено'

In [26]:
np.dot(A, B)

array([[11, 14, 17, 20],
       [23, 30, 37, 44],
       [35, 46, 57, 68]])

In [27]:
np.dot(B, A)

ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)