In [1]:
import numpy as np

__Задание 1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

*Вручную:*

$$\textbf{A}x=\lambda x$$

$$det(\textbf{A}-\lambda\textbf{I})=0$$

$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0$

$(-1-\lambda)(6-\lambda)+6\cdot2=0$

$(1+\lambda)(6-\lambda)-12=0$

$6 -\lambda + 6\cdot\lambda - \lambda^2 - 12 = 0$

$-\lambda^2 + 5\cdot\lambda - 6 = 0$

$\lambda^2 - 5\cdot\lambda + 6 = 0$

$D = 25 - 4 \cdot 6 = 1$

$\lambda_1 = \frac{5 + 1}{2} = 3$

$\lambda_2 = \frac{5 - 1}{2} = 2$

Собственные значения линейного оператора $A$ равны $(3, 2)$

$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda_{1}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$

$-x_1 - 6x_2 = 3x_1 \Rightarrow 4x_1=-6x_2 \Rightarrow x_1=-\frac{3}{2}x_2$

$2x_1 + 6x_2 = 3x_2 \Rightarrow 2x_1=-3x_2 \Rightarrow x_1=-\frac{3}{2}x_2$

При $x_1=3$ собственный вектор равен $\begin{pmatrix}
3\\ 
-2
\end{pmatrix}$ 

$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda_{2}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$

$-x_1 - 6x_2 = 2x_1 \Rightarrow -3x_1=-6x_2 \Rightarrow x_1=-2x_2$

$2x_1 + 6x_2 = 2x_2 \Rightarrow 2x_1=-4x_2 \Rightarrow x_1=-2x_2$

При $x_1=2$ собственный вектор равен $\begin{pmatrix}
2\\ 
-1
\end{pmatrix}$ 

*С помощью numpy:*

In [2]:
A = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(A)

w, v

(array([2., 3.]),
 array([[-0.89442719,  0.83205029],
        [ 0.4472136 , -0.5547002 ]]))

In [3]:
v[0, 1] / v[1, 1]

-1.4999999999999996

In [4]:
v[0, 0] / v[1, 0]

-2.0

__Задание 2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$

$-x_1 = \lambda x_1 \Rightarrow \lambda = -1$ при любых $x_1$

$-x_2 = \lambda x_2 \Rightarrow \lambda = -1$ при любых $x_2$

Следовательно, для линейного оператора
$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}$
любой вектор
$\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$
является собственным.

__Задание 3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

*Вручную:*

$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\
1
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}$

$\begin{cases}
1+1=1\cdot\lambda \\ 
-1+3=1\cdot\lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}$

Вектор $x=(1,1)$ является собственным вектором линейного оператора, заданного матрицей $A$, его собственное значение $\lambda=2.$

*С помощью numpy:*

In [5]:
A = np.array([[1, 1], [-1, 3]])
x = np.array([1, 1])

w, v = np.linalg.eig(A)

In [6]:
print(np.dot(A, x))

[2 2]


In [7]:
print(*(np.dot(i, x) for i in w))

[2.00000002 2.00000002] [1.99999998 1.99999998]


__Задание 4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

*Вручную:*

$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}$

$\begin{cases}
-9\lambda=3\\ 
9\lambda=-3\\
-12\lambda=-4
\end{cases}
\Rightarrow
\begin{cases}
\lambda=-3\\ 
\lambda=-3\\
\lambda=3
\end{cases}$

Вектор $x=(3, -3, -4)$ не является собственным вектором линейного оператора, заданного матрицей $A.$

*С помощью numpy:*

In [8]:
A = np.array([
    [0, 3, 0],
    [3, 0, 0],
    [0, 0, 3]])
x = np.array([3, -3, -4])

w, v = np.linalg.eig(A)

In [9]:
print(np.dot(A, x))

[ -9   9 -12]


In [10]:
print(*(np.dot(i, x) for i in w))

[  9.  -9. -12.] [-9.  9. 12.] [  9.  -9. -12.]
