In [1]:
import numpy as np

__Задание 1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & 1 & -1 & -5 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
2\\
4
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & 1 & -1 & -5 \\ 
0 & 0 & 2 & -3
\end{matrix}\right|
\begin{matrix}
0\\ 
2\\
-4
\end{matrix}
\end{pmatrix}
$

$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
\quad \; x_{2}-x_{3}-5x_{4}=2, \\
\qquad \quad \; 2x_{3}-3x_{4}=-4.
\end{cases}$

$\begin{cases}
x_{4}=c, \\
2x_{3}-3c=-4 \; \Leftrightarrow \; x_{3}=\frac{3c-4}{2}=1.5c-2, \\
x_{2} - 1.5c+2 - 5c=2 \; \Leftrightarrow \; x_{2} = 1.5c + 5c=6.5c, \\
x_{1} + 6.5c - 1.5c+2 -2c=0 \; \Leftrightarrow \; x_{1} = -3c-2.
\end{cases}$

*Общее решение системы:*

$\begin{cases}
x_{1} = -3c-2, \\
x_{2} = 6.5c, \\
x_{3} = 1.5c-2, \\
x_{4}=c.
\end{cases}$

__Задание 2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$


а)

In [2]:
A = np.array([
    [3, -1, 1],
    [2, -5, -3],
    [1, 1, -1]])

b = np.array([[4, -17, 0]])

In [3]:
A_ext = np.hstack((A, b.T))

A_ext

array([[  3,  -1,   1,   4],
       [  2,  -5,  -3, -17],
       [  1,   1,  -1,   0]])

In [4]:
np.linalg.matrix_rank(A) == np.linalg.matrix_rank(A_ext) == A.shape[1]

True

$rankA=rank \tilde A = n \Rightarrow$ система определена и имеет единственное решение.

In [5]:
np.linalg.solve(A, b[0])

array([1., 2., 3.])

б)

In [6]:
A = np.array([
    [2, -4, 6],
    [1, -2, 3],
    [3, -6, 9]])

b = np.array([[1, -2, 5]])

In [7]:
A_ext = np.hstack((A, b.T))

A_ext

array([[ 2, -4,  6,  1],
       [ 1, -2,  3, -2],
       [ 3, -6,  9,  5]])

In [8]:
np.linalg.matrix_rank(A) == np.linalg.matrix_rank(A_ext) == A.shape[1]

False

In [9]:
np.linalg.matrix_rank(A) < np.linalg.matrix_rank(A_ext)

True

$rank A < rank \tilde A \Rightarrow$ система несовместна.

в)

In [10]:
A = np.array([
    [1, 2, 5],
    [3, 1, -8]])

b = np.array([[4, -2]])

In [11]:
A_ext = np.hstack((A, b.T))

A_ext

array([[ 1,  2,  5,  4],
       [ 3,  1, -8, -2]])

In [12]:
np.linalg.matrix_rank(A) == np.linalg.matrix_rank(A_ext) == A.shape[1]

False

In [13]:
np.linalg.matrix_rank(A) == np.linalg.matrix_rank(A_ext) < A.shape[1]

True

$rankA =rank \tilde A < n \Rightarrow $ система имеет бесконечное количество решений.

__Задание 3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

Т.к. матрица $A$ является треугольной, то $rankA=rank \tilde A = n \Rightarrow$ система определена и имеет единственное решение.

In [14]:
A_ext = np.array([
    [1, 3, -2, 4, 3],
    [0, 5, 0, 1, 2],
    [0, 0, 3, 0, 4],
    [0, 0, 0, 2, 1]])

In [15]:
A = A_ext[:, :4]
b = A_ext[:, 4]

A, b

(array([[ 1,  3, -2,  4],
        [ 0,  5,  0,  1],
        [ 0,  0,  3,  0],
        [ 0,  0,  0,  2]]),
 array([3, 2, 4, 1]))

In [16]:
np.linalg.matrix_rank(A) == np.linalg.matrix_rank(A_ext) == A.shape[1]

True

In [17]:
np.linalg.solve(A, b)

array([2.76666667, 0.3       , 1.33333333, 0.5       ])

__Задание 4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & 3 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
4a-b\\
c
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & 3 & 6\\ 
0 & 6 & 12
\end{matrix}\right|
\begin{matrix}
a\\ 
4a-b\\
7a-c
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & 3 & 6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
4a-b\\
8a-2b-7a+c
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & 3 & 6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
4a-b\\
a-2b+c
\end{matrix}
\end{pmatrix}$

Следовательно, при значениях $a-2b+c \neq 0$ система будет являться несовместной.