In [1]:
import numpy as np
import scipy.linalg
import warnings
warnings.filterwarnings('ignore')

__Задание 1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

а)

In [2]:
A = np.array([[1, -2], 
              [3, -4]])

b = np.array([1, 7])

In [3]:
det_A = np.linalg.det(A)

det_A.round()

2.0

In [4]:
A1 = A.copy()
A1[:, 0] = b

A2 = A.copy()
A2[:, 1] = b

A1, A2

(array([[ 1, -2],
        [ 7, -4]]),
 array([[1, 1],
        [3, 7]]))

In [5]:
det_A1 = np.linalg.det(A1)
det_A2 = np.linalg.det(A2)

In [6]:
print(f'x1 = {det_A1 / det_A:.1f}\nx2 = {det_A2 / det_A:.1f}')

x1 = 5.0
x2 = 2.0


*Проверка:*

In [7]:
np.linalg.solve(A, b)

array([5., 2.])

б)

In [8]:
A = np.array([[2, -1, 5],
              [1, 1, -3],
              [2, 4, 1]])

b = np.array([10, -2, 1])

In [9]:
det_A = np.linalg.det(A)

det_A.round()

43.0

In [10]:
dict_A = {'A1': A.copy() ,'A2': A.copy(), 'A3': A.copy()}

for i in range(A.shape[1]):
    dict_A[f'A{i + 1}'][:, i] = b   

In [11]:
dict_A

{'A1': array([[10, -1,  5],
        [-2,  1, -3],
        [ 1,  4,  1]]),
 'A2': array([[ 2, 10,  5],
        [ 1, -2, -3],
        [ 2,  1,  1]]),
 'A3': array([[ 2, -1, 10],
        [ 1,  1, -2],
        [ 2,  4,  1]])}

In [12]:
for i in range(A.shape[1]):
    print(f'x{i + 1} = {np.linalg.det(dict_A[f"A{i + 1}"]) / det_A:.1f}')

x1 = 2.0
x2 = -1.0
x3 = 1.0


*Проверка:*

In [13]:
np.linalg.solve(A, b)

array([ 2., -1.,  1.])

__Задание 2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

а)

$U = \begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}=
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
3 & 26 & 30
\end{pmatrix}=
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}=
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$  

$L = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$

    

*Проверка:*

In [14]:
U = np.array([[1, 2, 4],
              [0, 5, 4],
              [0, 0, 2]])

L = np.array([[1, 0, 0],
              [2, 1, 0],
              [3, 4, 1]])

L @ U

array([[ 1,  2,  4],
       [ 2,  9, 12],
       [ 3, 26, 30]])

б)

$U = \begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}=
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}=
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}=
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$  

$L = \begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}$  

*Проверка:*

In [15]:
U = np.array([[1, 1, 2, 4],
              [0, 3, 4, 1],
              [0, 0, 3, 1],
              [0, 0, 0, 4]])

L = np.array([[1, 0, 0, 0],
              [2, 1, 0, 0], 
              [3, 5, 1, 0], 
              [4, 6, 7, 1]])

L @ U

array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])

__Задание 3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$


In [16]:
A = np.array([[2, 1, 3],
              [11, 7, 5],
              [9, 8, 4]])

b = np.array([1, -6, -5])

$$LUx=b$$

In [17]:
L, U = scipy.linalg.lu(A, permute_l=True)

L, U

(array([[ 0.18181818, -0.12      ,  1.        ],
        [ 1.        ,  0.        ,  0.        ],
        [ 0.81818182,  1.        ,  0.        ]]),
 array([[11.        ,  7.        ,  5.        ],
        [ 0.        ,  2.27272727, -0.09090909],
        [ 0.        ,  0.        ,  2.08      ]]))

In [18]:
np.allclose(L @ U, A)

True

$$Ly=b \Rightarrow y=L^{-1}b$$

In [19]:
y = np.linalg.inv(L).dot(b)

y.round(5)

array([-6.     , -0.09091,  2.08   ])

$$Ux=y \Rightarrow x=U^{-1}y$$

In [20]:
x = np.linalg.inv(U).dot(y)

x.round(5)

array([-1., -0.,  1.])

*Проверка:*

In [21]:
np.linalg.solve(A, b)

array([-1.,  0.,  1.])

__Задание 4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

In [22]:
A = np.array([[81, -45, 45],
              [-45, 50, -15],
              [45, -15, 38]])

b = np.array([531, -460, 193])

$$Ax=LL^{T}x=Ly=b$$

In [23]:
L = np.linalg.cholesky(A)
L, L.T

(array([[ 9.,  0.,  0.],
        [-5.,  5.,  0.],
        [ 5.,  2.,  3.]]),
 array([[ 9., -5.,  5.],
        [ 0.,  5.,  2.],
        [ 0.,  0.,  3.]]))

In [24]:
np.allclose(L @ L.T, A)

True

$$Ly=b \Rightarrow y=L^{-1}b$$

In [25]:
L_inv = np.linalg.inv(L)
y = L_inv.dot(b)

y

array([ 59., -33., -12.])

$$L^{T}x=y \Rightarrow x=(L^{-1})^Ty$$

In [26]:
x = L_inv.T.dot(y)

x

array([ 6., -5., -4.])

*Проверка:*

In [27]:
np.linalg.solve(A, b)

array([ 6., -5., -4.])

__Задание 5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [28]:
def gauss(A):
    
    n = len(A[0]) - 1
    x = [0 for _ in range(n)]
        
    for i in range(n):
        
        if A[i][i] == 0:
            raise SystemExit('Система имеет бесконечное множество решений либо не определена')

        for j in range(i + 1, n):
            ratio = A[j][i] / A[i][i]

            for k in range(n + 1):
                A[j][k] -= ratio * A[i][k]

    x[n - 1] = A[n - 1][n] / A[n - 1][n - 1]

    for i in range(n - 2, -1, -1):

        x[i] = A[i][n]

        for j in range(i + 1, n):
            x[i] -= A[i][j] * x[j]

        x[i] /= A[i][i]

    for i in range(n):
        print(f'x{i + 1} = {x[i]}')

In [29]:
A_ext = [[2, 1, 3, 1],
         [11, 7, 5, -6],
         [9, 8, 4, -5]]

gauss(A_ext)

x1 = -1.0
x2 = 0.0
x3 = 1.0


In [30]:
A_ext = [[81, -45, 45, 531],
         [-45, 50, -15, -460],
         [45, -15, 38, 193]]

gauss(A_ext)

x1 = 6.0
x2 = -5.0
x3 = -4.0


In [31]:
A_ext = [[2, -4,  6,  1],
         [1, -2,  3, -2],
         [3, -6,  9,  5]]

gauss(A_ext)

SystemExit: Система имеет бесконечное множество решений либо не определена