In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

**Задание 1.** Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [2]:
A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])

$$A=UDV^{T}$$

In [3]:
U, s, W = np.linalg.svd(A)

In [4]:
U

array([[ 0.17,  0.16, -0.53, -0.8 , -0.16],
       [ 0.39, -0.53,  0.61, -0.43,  0.03],
       [-0.14, -0.82, -0.52,  0.14,  0.07],
       [ 0.89,  0.06, -0.25,  0.38, -0.06],
       [ 0.08,  0.11, -0.08, -0.11,  0.98]])

In [5]:
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

D

array([[8.82, 0.  , 0.  ],
       [0.  , 6.14, 0.  ],
       [0.  , 0.  , 2.53],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ]])

In [6]:
V = W.T

V

array([[ 0.07, -0.37, -0.93],
       [ 0.72,  0.67, -0.21],
       [ 0.69, -0.65,  0.31]])

In [7]:
U @ D @ V.T

array([[ 1.,  2.,  0.],
       [ 0., -0.,  5.],
       [ 3., -4.,  2.],
       [ 1.,  6.,  5.],
       [-0.,  1., -0.]])

In [8]:
np.allclose(U @ D @ V.T, A)

True

**Задание 2.** Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

а)

In [9]:
s[0]

8.824868854820444

*Проверка*

In [10]:
np.linalg.norm(A, ord=2)

8.824868854820444

б)

In [11]:
np.sqrt(np.square(s).sum())

11.045361017187263

*Проверка*

In [12]:
np.linalg.norm(A, ord='fro')

11.045361017187261