In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
iris_frame = pd.DataFrame(iris.data)
iris_frame.columns = iris.feature_names
iris_frame['target'] = iris.target
iris_frame['name'] = iris_frame.target.apply(lambda x : iris.target_names[x])

iris_frame

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target       name  
0         0     setosa  
1         0     setosa  
2         0     setosa  
3         0     setosa  
4         0     setosa  
..      ...        ...  
145       2  virginica  
146       2  virginica  
147       2  virginica  
148       2  virginica  
149       2  virginica  

[150 rows x 6 columns]

In [3]:
X = iris_frame.drop(columns=['target', 'name'])

In [4]:
U, s, W = np.linalg.svd(X)
D = np.zeros_like(X, dtype=float)
D[np.diag_indices(min(X.shape))] = s
V = W.T

In [5]:
D[:4]

array([[95.95991387,  0.        ,  0.        ,  0.        ],
       [ 0.        , 17.76103366,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  3.46093093,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.88482631]])

In [6]:
variance = np.var(X, axis=0, ddof=1).sum()

variance

4.572957046979867

In [7]:
D[3, 3] = 0
D[:4]

array([[95.95991387,  0.        ,  0.        ,  0.        ],
       [ 0.        , 17.76103366,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  3.46093093,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [8]:
X1 = U @ D @ V.T

variance1 = np.var(X1, axis=0, ddof=1).sum()

In [9]:
print(f'При уменьшении количества коррелированных признаков на 1 доля потерянной информации составляет \
{(1 - variance1 / variance) * 100:.2f}%')

При уменьшении количества коррелированных признаков на 1 доля потерянной информации составляет 0.52%


In [10]:
D[2, 2] = 0
D[:4]

array([[95.95991387,  0.        ,  0.        ,  0.        ],
       [ 0.        , 17.76103366,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [11]:
X2 = U @ D @ V.T

variance2 = np.var(X2, axis=0, ddof=1).sum()

In [12]:
print(f'При уменьшении количества коррелированных признаков на 2 доля потерянной информации составляет \
{(1 - variance2 / variance) * 100:.2f}%')

При уменьшении количества коррелированных признаков на 2 доля потерянной информации составляет 2.28%
